version: '3'

services: 
  db:
    build: ./db
  payment-server:
    build: ./payment-server
    ports:
      - "3000:3000"
    restart: on-failure
  subscription-server:
    build: ./subscription-server
    ports:
      - "3001:3001"
    depends_on:
      - db
      - payment-server
    restart: on-failure
    